name: Voop
options:
  bundleIdPrefix: com.galaiko
  deploymentTarget:
    iOS: "26.0"
  defaultConfig: Debug
  xcodeVersion: "16.4"

settings:
  base:
    SWIFT_VERSION: 6.0
    ENABLE_STRICT_CONCURRENCY: complete
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  Voop:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Voop
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.galaiko.voop
        DEVELOPMENT_TEAM: YT4992HVGM
        INFOPLIST_FILE: Voop/App/Info.plist
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - framework: VoopProtocol.xcframework
        embed: false
